### ISSUE TITLE
ImportError: No module named packaging

### ISSUE THREAD

**Issue by tungngovn** [AIR-Hust/respeaker_ros#6]
```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/catkin_virtualenv/combine_requirements", line 27, in <module>
    from packaging.requirements import Requirement, InvalidRequirement
  File "/home/tungngo/ros/local/lib/python2.7/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
    raise ImportError("No module named %s" % modulename)
ImportError: No module named packaging
```

**Comment by tungngovn** [comment]
`pip install packaging`
